language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get update
- sudo apt-get install imagemagick
- gem install sass
- npm install -g bower
- npm install -g grunt-cli
before_script:
- bower install
script:
- grunt deploy --production
deploy:
  provider: s3
  access_key_id: AKIAI3CX3YB3KYLZ5S3A
  secret_access_key:
    secure: PzgcgVQ8N86K2I2zLz2PieS6CiPXOCeybh77ilevN2knHLb8UYzXFvut+UNw5/Fi8wLaul8oBLoJth2ozr9YebtpNJguOU8ldYFThj/Acgjd9HaFoux+w+KUHp3MFcRfYblP5pAVMaYFbxeOpjd2plQ6jHE4rA6w//i1/UBBoXs=
  bucket: furzeface.com
  skip_cleanup: true
  endpoint: http://furzeface.com.s3-website-eu-west-1.amazonaws.com/
  region: eu-west-1
  local-dir: dist
  on:
    branch: master
    repo: furzeface/furzeface.com
after_deploy:
  - grunt post_deploy
